-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
from REST_INFO
where (FAVORITES, REST_ID) in (
    select max(FAVORITES) as FAVORITES, REST_ID from REST_INFO group by FOOD_TYPE
)
order by FOOD_TYPE DESC;

# select max(FAVORITES) as FAVORITES, REST_ID from REST_INFO group by FOOD_TYPE