-- 코드를 입력하세요
SELECT o.PRODUCT_ID, p.PRODUCT_NAME, p.price * count(p.PRODUCT_NAME) as TOTAL_SALES
FROM FOOD_PRODUCT p
    LEFT JOIN FOOD_ORDER o
    ON o.PRODUCT_ID = p.PRODUCT_ID
where o.PRODUCE_DATE like "2022-05-%"
group by p.PRODUCT_NAME
order by TOTAL_SALES desc, o.PRODUCT_ID asc;