-- 코드를 작성해주세요
# SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
# FROM ITEM_INFO I
#     INNER JOIN ITEM_TREE T
# WHERE I.RARITY = 'RARE'
# ORDER BY I.ITEM_ID DESC;


SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT T.ITEM_ID
    FROM ITEM_TREE T, ITEM_INFO I
    WHERE I.ITEM_ID = T.PARENT_ITEM_ID and I.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC;



# SELECT T.ITEM_ID, I.ITEM_NAME
# FROM ITEM_INFO I, ITEM_TREE T
# WHERE I.ITEM_ID = T.ITEM_ID and I.RARITY = 'RARE'
# ORDER BY I.ITEM_ID DESC;