-- 코드를 입력하세요
# SELECT f.FLAVOR
# FROM FIRST_HALF f, ICECREAM_INFO i
# WHERE i.INGREDIENT_TYPE = 'fruit_based' ;

SELECT DISTINCT f.FLAVOR
FROM FIRST_HALF f
LEFT OUTER JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
WHERE i.INGREDIENT_TYPE = 'fruit_based' and f.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;
